### ISSUE TITLE
[starling] Animation with curve doesn't play

### ISSUE THREAD

**Issue by ilushaaa** [EsotericSoftware/spine-runtimes#1569]
Hello,

Issue is described here: http://esotericsoftware.com/forum/Starling-Clipping-doesn-t-work-10139

I have two animations which don't play in Starling runtime.
Also they don't work in the skeletonViewer.

One of them falls with exception when loading:

`com.badlogic.gdx.utils.SerializationException: Error reading animation: initial.idle
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:348)
        at com.esotericsoftware.spine.SkeletonViewer.loadSkeleton(SkeletonViewer.java:207)
        at com.esotericsoftware.spine.SkeletonViewer$UI$2.changed(SkeletonViewer.java:705)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:131)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:94)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: java.lang.NullPointerException
        at com.esotericsoftware.spine.SkeletonJson.readCurve(SkeletonJson.java:901)
        at com.esotericsoftware.spine.SkeletonJson.readTimeline(SkeletonJson.java:883)
        at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:630)
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:346)
        ... 14 more`

Animations were sent to the Esoteric Software email.

**Comment by spayton** [comment]
I'm, also getting skeletonviewer problems with customer spine exports so went back and tries some from the examples.  So I tried the current skeletonviewer.jar (3.8.76) with example spineboy-pro (3.8.55) and get loading failure with this in console:

`com.badlogic.gdx.utils.SerializationException: Error reading animation: hoverboard
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:348)
        at com.esotericsoftware.spine.SkeletonViewer.loadSkeleton(SkeletonViewer.java:207)
        at com.esotericsoftware.spine.SkeletonViewer$UI$2.changed(SkeletonViewer.java:705)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
        at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:131)
        at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:94)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:88)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:59)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:351)
        at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:360)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:221)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
Caused by: java.lang.NullPointerException
        at com.esotericsoftware.spine.SkeletonJson.readCurve(SkeletonJson.java:901)
        at com.esotericsoftware.spine.SkeletonJson.readTimeline(SkeletonJson.java:883)
        at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:627)
        at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:346)
        ... 14 more`

my java version reports:
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

**Comment by badlogic** [comment]
Please give the latest SkeletonViewer 3.8.80 a try, it should work as intended. @ilushaaa I have updated the forum thread with my findings. I'm afraid I can not reproduce your issue.
