### ISSUE TITLE
Skeleton Viewer can't run

### ISSUE THREAD

**Issue by cwoandrew** [EsotericSoftware/spine-runtimes#1848]
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:134)
Caused by: java.lang.NoSuchMethodError: java.nio.FloatBuffer.flip()Ljava/nio/FloatBuffer;
        at com.badlogic.gdx.graphics.glutils.VertexArray.<init>(VertexArray.java:59)
        at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:187)
        at com.badlogic.gdx.graphics.Mesh.<init>(Mesh.java:158)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:103)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
        at com.badlogic.gdx.scenes.scene2d.Stage.<init>(Stage.java:101)
        at com.esotericsoftware.spine.SkeletonViewer$UI.<init>(SkeletonViewer.java:436)
        at com.esotericsoftware.spine.SkeletonViewer.create(SkeletonViewer.java:126)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:150)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

**Comment by badlogic** [comment]
What Java version are you using? This error indicates that you might be running Java 6 or 7.

**Comment by cwoandrew** [comment]
fixed, thanks

在 2021年2月24日週三 01:12，Mario Zechner <notifications@github.com> 寫道：
