### ISSUE TITLE
[libgdx] SimpleTests crash; SpriteBatch cannot render meshes

### ISSUE THREAD

**Issue by soundasleep** [EsotericSoftware/spine-runtimes#1886]
Hello!

Brand new to libgdx and spine's worlds. I'm trying to get [SimpleTest1.java](https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-libgdx/spine-libgdx-tests/src/com/esotericsoftware/spine/SimpleTest1.java) working locally (using libgdx 1.9.14, lwjgl 2.9.3, spine-libgdx 3.8.55.1) but when I try to run SimpleTest1.java in my project I get:

```
Exception in thread "LWJGL Application" java.lang.RuntimeException: SpriteBatch cannot render meshes, PolygonSpriteBatch or TwoColorPolygonBatch is required.
	at com.esotericsoftware.spine.SkeletonRenderer.draw(SkeletonRenderer.java:133)
	at org.jevon.onitest.gdx.SimpleTest1.render(SimpleTest1.java:78)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
```

Has the API changed? Do the tests applications need to be updated?

**Comment by soundasleep** [comment]
After a bit more investigation, if you use `"spineboy/spineboy-ess.skel"` (Essentials) instead of `"spineboy/spineboy-pro.skel"` (Pro) then you can load it into a SpriteBatch fine.

**Comment by badlogic** [comment]
Ah, the batch needs to be a `PolygonSpriteBatch` not a standard `SpriteBatch` here:
https://github.com/EsotericSoftware/spine-runtimes/blob/3.8/spine-libgdx/spine-libgdx-tests/src/com/esotericsoftware/spine/SimpleTest1.java#L52
