### ISSUE TITLE
[runtimes] Import error on reading bezier curves

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1930]
As reported via email, reproduction Spine project included:
FMfcgzGkZZlxBqcXxSJdWsTBjRHfcplb
([Edit: Added second report] Similar project with the same exception reported via this email:
FMfcgzGkbDThpmdllxwzRFDtklmtLmXx)

Verified in SkeletonViewer and spine-unity. This issue only occurs when exporting and importing the skeleton as json, it does not occur on binary export. Spine 4.0.16 used to export the files.

To reproduce, open the project `01...spine` in Spine and export as `.json`, then open the `.json` file in SkeletonViewer to receive the exception.

An array index out-of-bounds exception thrown here:
```
Error loading skeleton: C:\Spine\UnityProjects\SpineUnity2021.2_Testing\Assets\ForumTesting\jsonGmail\reexport\01SlimeEro.json
com.badlogic.gdx.utils.SerializationException: Error reading animation: ????/15F2  // note: this is animation ピストン/15F2
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:349)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:107)
	at com.esotericsoftware.spine.SkeletonViewer.loadSkeleton(SkeletonViewer.java:137)
	at com.esotericsoftware.spine.SkeletonViewerUI$2.changed(SkeletonViewerUI.java:334)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:125)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:93)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:71)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:355)
	at com.badlogic.gdx.InputMultiplexer.touchUp(InputMultiplexer.java:124)
	at com.badlogic.gdx.backends.lwjgl.DefaultLwjglInput.processEvents(DefaultLwjglInput.java:312)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:220)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 730 out of bounds for length 730
	at com.esotericsoftware.spine.Animation$CurveTimeline.setBezier(Animation.java:341)
	at com.esotericsoftware.spine.SkeletonJson.setBezier(SkeletonJson.java:1045)
	at com.esotericsoftware.spine.SkeletonJson.readCurve(SkeletonJson.java:1039)
	at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:798)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:347)
	... 15 more
```

**Comment by NathanSweet** [comment]
4.0.25
