### ISSUE TITLE
Bezier-curve related import error when exported with `Animation cleanup`

### ISSUE THREAD

**Issue by HaraldCsaszar** [EsotericSoftware/spine-runtimes#1951]
Reproduction project is contained in this email thread, first mail:
FMfcgzGkbDfvckWcFxWlsTWzFhMXsTDw
From that gdrive directory, the following files should be relevant:
"20210830 Spine3.8維持　Estherのみ独立.spine" and the "images" dir.

Error occurs when opening the project in Spine Editor version 4.0.30 and exporting with `Animation cleanup`, no error occurs upon import when exported with `Animation cleanup` disabled.

Perhaps related to #1930?
Exception:
```
Error loading skeleton: C:\Spine\BugreportReproZipFiles\20210906_SpineProjectCorruptMaybe\2\Test 4.0 Spine_Unity\Assets\Test_Spine4.0\4.028 & Debugged skin alert\Esther.json
com.badlogic.gdx.utils.SerializationException: Error reading animation: Atk3a
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:349)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:107)
	at com.esotericsoftware.spine.SkeletonViewer.loadSkeleton(SkeletonViewer.java:137)
	..
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 365 out of bounds for length 365
	at com.esotericsoftware.spine.Animation$CurveTimeline.setBezier(Animation.java:341)
	at com.esotericsoftware.spine.SkeletonJson.setBezier(SkeletonJson.java:1045)
	at com.esotericsoftware.spine.SkeletonJson.readCurve(SkeletonJson.java:1039)
	at com.esotericsoftware.spine.SkeletonJson.readAnimation(SkeletonJson.java:796)
	at com.esotericsoftware.spine.SkeletonJson.readSkeletonData(SkeletonJson.java:347)
```

**Comment by NathanSweet** [comment]
Fixed in: dc9a6ebe7fb11f8cf5f398fe43cda52d77569d85
