### ISSUE TITLE
Q: How to convert spine json file to binary

### ISSUE THREAD

**Issue by JCash** [EsotericSoftware/spine-runtimes#1959]
Hi!

I'm wondering if it's possible today (or in future) to convert a spine json file to binary file using the C/C++ api.

Our use case is to let users store their exported files in json format in their projects, but also let us convert to the current binary format in our build pipeline tools. That way we can save some storage and loading times for the end users.

Regards,
Mathias

**Comment by badlogic** [comment]
This is not a feature we will support. You can import .json fioes and re-export them as .skel files via the editor command line interface: http://en.esotericsoftware.com/spine-command-line-interface

**Comment by wayaya19851103** [comment]
Hi！

I also have this problem. When I execute this command, spine was opened, but no data imported, and stop at step1.

If I import data in the editor(spine 3.6.52), it‘s worked.

How do I write this command line....

-------------------------------------------------------------------------------
echo --step1
Spine -i H:\test_mosaic\13poxiedajian.json -o H:\test_mosaic\output.spine -r 13poxiedajian
echo --step2
Spine -i H:\test_mosaic\output.spine -o H:\test_mosaic\SpineExport -e H:\test_mosaic\spinesetting.export.json
echo --step3

**Comment by badlogic** [comment]
Add -u 3.6.52 to step1, that will import the project via that editor version.

**Comment by wayaya19851103** [comment]
> Add -u 3.6.52 to step1, that will import the project via that editor version.

Its not worked...
Step1 is to open the last closed spine every time, not open my output.spine

**Comment by badlogic** [comment]
What Spine Launcher version are you using?

**Comment by ModischFabrications** [comment]
Just checking in to note that a feature to convert json to binary would be much appreciated. We have a huge runtime cost of deserializing json's on startup and would like to use binary files to circumvent it. Re-Exporting from spine is not viable for us because they are spread between multiple directories and from multiple source files. I would ideally use it as a Editor script in Unity, but it's fine to call from CLI instead, as long as it's "batchable"

**Comment by badlogic** [comment]
You should be able to do exactly that using the Spine Editor CLI interface:
http://en.esotericsoftware.com/spine-command-line-interface

See the import and export sections. Here's how to do it for one file:

1. Create a file called `binary.json` and paste the following content into it:
```
{
"class": "binary",
"extension": ".skel",
"nonessential": "true"
}
```
2. Import the skeleton's `.json` file into a temporary Spine project: `Spine.exe -i skeleton.json -o temp.spine -r`
3. Export the skeleton in the temporary Spine project to binary: `Spine.exe -i temp.spine -o /path/to/export/to` -e binary.json

You can batch this as well by chaining the commands, e.g. 
```
Spine -i t_transition.json -o output.spine -r -i output.spine -o $(pwd) -e binary.json
```

You can even chain the import/export of multiple files in one invocation of the Spine executable if you provide a different name for each temporary Spine project file.

**Comment by ModischFabrications** [comment]
I am trying to get it running but get a few errors:

1. When running in two steps I get `Images path not found: ./<directory of file>/`, but the export works. This takes forever due to starting and stopping of spine and is somewhat irritating because I am unsure if the warning can be ignored.
2. When running as a chain I get `ERROR: Input path does not exist: <temp spine file>` and the export crashes. It seems to me that the export checks for it's input before the first part of the chain is able to create it. 

Are there any tricks I am missing?

**Comment by badlogic** [comment]
Please show your full command and also show me what your inout file folder
hierarchy looks like.

**Comment by ModischFabrications** [comment]
<details>
<summary>convert_spine.sh</summary>

```
#!/bin/bash

# Made by Robin Modisch, 2023/01/26
# call with `convert_spine.sh ./Assets` in git bash , make sure to keep binary.json in the same directory as the script
# Needs a few additional steps in Unity to convert files:
# 1. Execute script
# 2. Open unity to generate meta files
# 3. For each: Copy guid of new file to SkeletonData.asset->skeletonJSON

# inspired by these: 
# - http://en.esotericsoftware.com/spine-command-line-interface
# - https://github.com/EsotericSoftware/spine-runtimes/blob/4.1/examples/export/export.sh
# - https://github.com/EsotericSoftware/spine-runtimes/issues/1959#issuecomment-1404833818

# fail fast
set -e

directory="$1"
# check with `Spine.exe -i <file-path>` or from json
version="3.8.99"
exportconfig=$(readlink -f "binary.json")

cd "$directory"

# Use the find command to search for files recursively
find . -type f -name "*.json" | while read file; do
  # check for spine file
  if [[ $(head -c 30 ${file} | tr -d '[[:space:]]') != '{"skeleton":'* ]]; then
    echo -n "."
    continue
  fi
  echo "Converting and removing '${file}'"

  # Get the file name and extension
  directory=$(dirname $file)

  tmpfile="$(mktemp).spine"
  echo "Saving tmp file to ${tmpfile}"
  Spine.com -u "${version}" -i "${file}" -o "${tmpfile}" -r
  Spine.com -u "${version}" -i "${tmpfile}" --clean -o "${directory}" -e "${exportconfig}"
  # WIP, chain as many as you want
  #Spine.com -u "${version}" -i "${file}" -o "${tmpfile}" -r -i "${tmpfile}" --clean -o "${directory}" -e "${exportconfig}"
  rm "${tmpfile}" "${file}"
done
```
</details>

binary.json:
```
{
"class": "binary",
"extension": ".skel.bytes",
"nonessential": "true"
}
```

<details>
<summary>Example log: </summary>

```
Converting and removing './Avatars/Bases/Peitschendudes/Animation/Peischendude_rot.json'
Saving tmp file to /tmp/tmp.Lzf1v4zuvP.spine
Spine Launcher 4.1.10
Esoteric Software LLC (C) 2013-2022 | http://esotericsoftware.com
Windows 10 Pro amd64 10.0
Launching: Spine 3.8.99 Professional
Spine Launcher 4.1.10-legacy
Starting: Spine 3.8.99
Spine 3.8.99 Professional
Licensed to: NeoBird, info@factorsix.de
Project import: Peischendude_rot.json into tmp.Lzf1v4zuvP
Complete.
Spine Launcher 4.1.10
Esoteric Software LLC (C) 2013-2022 | http://esotericsoftware.com
Windows 10 Pro amd64 10.0
Launching: Spine 3.8.99 Professional
Spine Launcher 4.1.10-legacy
Starting: Spine 3.8.99
Spine 3.8.99 Professional
Licensed to: NeoBird, info@factorsix.de
Animation clean up (0): tmp.Lzf1v4zuvP
Binary export: tmp.Lzf1v4zuvP
Image for slot [slot: Body, bone: Hip] not found: images_Peitschendude_rot/K├╢rper
Image for slot [slot: Kopf, bone: Head] not found: images_Peitschendude_rot/Kopf
Image for slot [slot: Peitsche_Seitenarm_01, bone: right_UpperArm] not found: images_Peitschendude_rot/Peitsche_Seitenarm_01
Image for slot [slot: Peitsche_Seitenarm_02, bone: right_UpperArm] not found: images_Peitschendude_rot/Peitsche_Seitenarm_02
Image for slot [slot: linker Arm, bone: left_UpperArm] not found: images_Peitschendude_rot/linker Arm
Image for slot [slot: rechter Arm, bone: right_UpperArm] not found: images_Peitschendude_rot/rechter Arm
Image for slot [slot: right leg, bone: Hip] not found: images_Peitschendude_rot/rechtes Bein
Complete.
```
</details>

<details>
<summary>`ls Avatars/Bases/Peitschendudes/Animation/` (after running export, replace `.skel.bytes` with `.json` ) </summary>

```
 Peischendude_gelb.json.meta                 Peischendude_rot_SkeletonData.asset
 Peischendude_gelb.skel.bytes                Peischendude_rot_SkeletonData.asset.meta
 Peischendude_gelb_SkeletonData.asset        Peitschendude_blau.json.meta
 Peischendude_gelb_SkeletonData.asset.meta   Peitschendude_blau.skel.bytes
 Peischendude_grau.json.meta                 Peitschendude_blau_SkeletonData.asset
 Peischendude_grau.skel.bytes                Peitschendude_blau_SkeletonData.asset.meta
 Peischendude_grau_SkeletonData.asset       'Peitschendudes_Special Move_02.atlas.txt'
 Peischendude_grau_SkeletonData.asset.meta  'Peitschendudes_Special Move_02.atlas.txt.meta'
 Peischendude_grün.json.meta                'Peitschendudes_Special Move_02.png'
 Peischendude_grün.skel.bytes               'Peitschendudes_Special Move_02.png.meta'
 Peischendude_grün_SkeletonData.asset       'Peitschendudes_Special Move_02_Atlas.asset'
 Peischendude_grün_SkeletonData.asset.meta  'Peitschendudes_Special Move_02_Atlas.asset.meta'
 Peischendude_rot.json.meta                 'Peitschendudes_Special Move_02_Material.mat'
 Peischendude_rot.skel.bytes                'Peitschendudes_Special Move_02_Material.mat.meta'
```
</details>

"Images for slot not found" is also thrown for every other file, possibly the same error.

**Comment by badlogic** [comment]
The images for slot error is to be expected, as the source images aren't
available. The exported .skel will be fine though.

I'll investigate why the chained version gives errors based on your script.

**Comment by ModischFabrications** [comment]
Thanks, that's good to know, I will ignore the warnings in that case. 

Another problem is also that special characters, sometimes even spaces, cause the export to fail. Converting '<...>/Avatars/Bases/Berengar & Gertrude/Animation/Gertrude.json' will import fine, but the export step crashes with the following message:

**% not properly escaped**
```
ERROR: Unable to start: Spine 3.8.99
ERROR: An unexpected error has occurred:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.esotericsoftware.spine.editor.launcher.Launcher._(_:523)
        at com.esotericsoftware.spine.editor.launcher.Launcher.L(_:383)
        at com.esotericsoftware.spine.editor.launcher.Launcher.<init>(_:173)
        at s.Oml.run(_:880)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: Pk: java.io.IOException: Unable to create parent directories for path: <...>\Avatars\Bases
.
Gertrude\Animation\Gertrude.skel.bytes
        at OR.B(SourceFile:1203)
        at CB.run(SourceFile:57)
        at OR.B(SourceFile:1838)
        at Cz.D(SourceFile:48)
        at jp.D(SourceFile:95)
        at jp.D(SourceFile:64)
        at jp.D(SourceFile:49)
        at com.esotericsoftware.spine.editor.Editor.D(SourceFile:1815)
        at com.esotericsoftware.spine.editor.Editor.main(SourceFile:1776)
        ... 22 more
Caused by: java.io.IOException: Unable to create parent directories for path: <...>\Avatars\Bases
.
Gertrude\Animation\Gertrude.skel.bytes
        at OK.D(SourceFile:209)
        at OR.B(SourceFile:1200)
        ... 30 more
```

Converting '<...>/Avatars/Bases/Archer Minions/Animation/MinionArcher.json' // **spaces missing**
```
ERROR: Unable to start: Spine 3.8.99
ERROR: An unexpected error has occurred:
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.esotericsoftware.spine.editor.launcher.Launcher._(_:523)
        at com.esotericsoftware.spine.editor.launcher.Launcher.L(_:383)
        at com.esotericsoftware.spine.editor.launcher.Launcher.<init>(_:173)
        at s.Oml.run(_:880)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: Pk: java.io.IOException: Unable to create parent directories for path: '<...>\Avatars\Bases
Minions\Animation\MinionArcher.skel.bytes
        at OR.B(SourceFile:1203)
        at CB.run(SourceFile:57)
        at OR.B(SourceFile:1838)
        at Cz.D(SourceFile:48)
        at jp.D(SourceFile:95)
        at jp.D(SourceFile:64)
        at jp.D(SourceFile:49)
        at com.esotericsoftware.spine.editor.Editor.D(SourceFile:1815)
        at com.esotericsoftware.spine.editor.Editor.main(SourceFile:1776)
        ... 22 more
Caused by: java.io.IOException: Unable to create parent directories for path: '<...>\Avatars\Bases
Minions\Animation\MinionArcher.skel.bytes
        at OK.D(SourceFile:209)
        at OR.B(SourceFile:1200)
        ... 30 more
```

**Comment by badlogic** [comment]
That is most likely a problem with bash. Make sure to escape all arguments
you pass to Spine, so bash doesn't chop them up. Usually, just putting
double quotes around things does the trick.
