### ISSUE TITLE
[spine-ts]  Shader.ts:161 Uncaught Error: Shader not compiled.

### ISSUE THREAD

**Issue by swcleo** [EsotericSoftware/spine-runtimes#2391]
When I call game.destory(true) then  new Phaser.Game()  again，I got the Error message. Why?

```
Shader.ts:161 Uncaught Error: Shader not compiled.
    at _Shader.getUniformLocation (Shader.ts:161:28)
    at _Shader.setUniform4x4f (Shader.ts:156:28)
    at SceneRenderer.enableRenderer (SceneRenderer.ts:497:23)
    at SceneRenderer.begin (SceneRenderer.ts:86:8)
    at SpineGameObject.renderWebGL (SpineGameObject.ts:328:18)
    at WebGLRenderer2.render (phaser.js:179467:19)
    at CameraManager2.render (phaser.js:11746:26)
    at Systems2.render (phaser.js:195992:22)
    at SceneManager2.render (phaser.js:193230:21)
    at Game2.step (phaser.js:17202:20)
 ```

**Comment by swcleo** [comment]
Same Issue：https://github.com/EsotericSoftware/spine-runtimes/issues/2390
