### ISSUE TITLE
[UE4] Can't built for Android: undefined reference to 'vtable for USpineAtlasAsset'

### ISSUE THREAD

**Issue by GerodruS** [EsotericSoftware/spine-runtimes#906]
Example (https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-ue4) is working fine in editor, but I can't build it for android platform. Log:
```
LogPlayLevel: Launcher Device ID: Android_DXT@015d41d423500e14
LogPlayLevel: PlayLevel: No blueprints needed recompiling
LogCook:Display: Verify cooked packages: 
Packages considered for dependency checks: 345, 
Packages failed dependency checks 0, 
Found redirectors: 5, 
Packages Kept: 345, 
Packages Missing: 0, 
Packages Deleted: 0
LogCook:Display: Sandbox cleanup took 2.192 seconds for platforms AllDesktop MacClient MacNoEditor MacServer Mac WindowsClient WindowsNoEditor WindowsServer Windows Android Android_ASTC Android_ATC Android_DXT Android_ETC1 Android_ETC2 Android_Multi Android_PVRTC HTML5 IOS TVOS LinuxClient LinuxNoEditor LinuxServer Linux  iterative true
LogRedirectors:Display: Timer ResolveTimeLoad 1.637006
LogRedirectors:Display: Timer ResolveTimeDelegate 0.000000
LogRedirectors:Display: Timer ResolveTimeTotal 1.644181
LogBlueprintCodeGen:Display: Nativization Summary - AnimBP:
LogBlueprintCodeGen:Display: Name, Children, Non-empty Functions (Empty Functions), Variables, FunctionUsage, VariableUsage
LogBlueprintCodeGen:Display: Nativization Summary - Shared Variables From Graph: 0
LogBlueprintCodeGen: GenerateStubs - all unconverted bp: 0, generated wrapers: 0
LogChunkManifestGenerator: Starting FixupPackageDependenciesForChunks...
LogChunkManifestGenerator: Updated collection PackagesRemovedFromChunk0
LogChunkManifestGenerator: Chunk: 0, Started with 518 packages, Final after dependency resolve: 518
LogStats: ... FixupPackageDependenciesForChunks complete. -  0.001 s
LogChunkManifestGenerator:Display: Saving asset registry.
LogChunkManifestGenerator:Display: Generated asset registry num assets 375, size is 164.67kb
LogChunkManifestGenerator:Display: Done saving asset registry.
LogCook:Display: Cook by the book total time in tick 0.000096s total time 3.762892
LogCook:Display: Peak Used virtual 1767 Peak Used phsical 1834
LogCook:Display: Hierarchy timer information
Name:  Length(ms)Root: 0.000000ms
CleanSandboxTime: 2192.068111ms
StartupPackagesResolveStringAssetReferences: 212.394085ms
GenerateLongPackageName: 0.112038ms
SavingAssetRegistry: 231.298227ms
IntStats
SavedPackage=370
LoadPackage=18
LogPlayLevel: Completed Launch On Stage: Cooking in the editor, Time: 0.000051
LogPlayLevel: Running AutomationTool...
LogPlayLevel: Automation.ParseCommandLine: Parsing command line: -ScriptsForProject=C:/Unreal/spine-ue4/SpineUE4.uproject BuildCookRun -project=C:/Unreal/spine-ue4/SpineUE4.uproject -noP4 -clientconfig=Development -serverconfig=Development -nocompile -nocompileeditor -installed -ue4exe=UE4Editor-Cmd.exe -utf8output -platform=Android_DXT -targetplatform=Andro
id -cookflavor=DXT -build -map=/Game/GettingStarted/02-complex-animation -skipcook -CookInEditor -iterativecooking -compressed -iterativedeploy -stage -deploy -cmdline="/Game/GettingStarted/02-complex-animation -Messaging" -device=Android_DXT@015d41d423500e14 -addcmdline="-SessionId=FD0C514340C83FD86245D69411F4D1EB -SessionOwner='gerodrus' -SessionName='Laun
ch On Device' " -run
LogPlayLevel: Automation.Process: Setting up command environment.
LogPlayLevel: BuildCookRun.SetupParams: Setting up ProjectParams for C:\Unreal\spine-ue4\SpineUE4.uproject
LogPlayLevel: Project.Build: ********** BUILD COMMAND STARTED **********
LogPlayLevel: Completed Launch On Stage: Build Task, Time: 1.758952
LogPlayLevel: CommandUtils.Run: Run: C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe SpineUE4 Android Development -Project=C:\Unreal\spine-ue4\SpineUE4.uproject  C:\Unreal\spine-ue4\SpineUE4.uproject  -remoteini="C:\Unreal\spine-ue4" -noxge -generatemanifest -NoHotReload
LogPlayLevel: UnrealBuildTool: NDK version: 19, GccVersion: 4.9
LogPlayLevel: CommandUtils.Run: Run: Took 2,5561463s to run UnrealBuildTool.exe, ExitCode=0
LogPlayLevel: CommandUtils.Run: Run: C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe SpineUE4 Android Development -Project=C:\Unreal\spine-ue4\SpineUE4.uproject  C:\Unreal\spine-ue4\SpineUE4.uproject  -remoteini="C:\Unreal\spine-ue4" -noxge -NoHotReload -ignorejunk
LogPlayLevel: UnrealBuildTool: Performing 1 actions (2 in parallel)
LogPlayLevel: UnrealBuildTool: [1/1] clang++.exe SpineUE4-armv7-es2.so
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonAnimationComponent.cpp:110: error: undefined reference to 'USpineAtlasAsset::GetAtlas(bool)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonAnimationComponent.cpp:110: error: undefined reference to 'USpineSkeletonDataAsset::GetSkeletonData(spAtlas*, bool)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonAnimationComponent.cpp:112: error: undefined reference to 'USpineAtlasAsset::GetAtlas(bool)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonAnimationComponent.cpp:112: error: undefined reference to 'USpineSkeletonDataAsset::GetAnimationStateData(spAtlas*)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonComponent.cpp:186: error: undefined reference to 'USpineAtlasAsset::GetAtlas(bool)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonComponent.cpp:186: error: undefined reference to 'USpineSkeletonDataAsset::GetSkeletonData(spAtlas*, bool)'
LogPlayLevel: UnrealBuildTool: C:\Unreal\spine-ue4\Plugins\SpinePlugin\Source\SpinePlugin\Private/SpineSkeletonRendererComponent.cpp:84: error: undefined reference to 'USpineAtlasAsset::GetAtlas(bool)'
LogPlayLevel: UnrealBuildTool: C:/Unreal/spine-ue4/Plugins/SpinePlugin/Binaries/Android/UE4-SpinePlugin-armv7-es2.a(SpinePlugin.generated.cpp-armv7-es2.o):C:/Unreal/spine-ue4/Plugins/SpinePlugin/Intermediate/Build/Android/UE4/Inc/SpinePlugin/SpinePlugin.generated.cpp:function USpineAtlasAsset::USpineAtlasAsset(FVTableHelper&): error: undefined reference to '
vtable for USpineAtlasAsset'
LogPlayLevel: UnrealBuildTool: C:/NVPACK/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
LogPlayLevel: UnrealBuildTool: C:/Unreal/spine-ue4/Plugins/SpinePlugin/Binaries/Android/UE4-SpinePlugin-armv7-es2.a(SpinePlugin.generated.cpp-armv7-es2.o):C:/Unreal/spine-ue4/Plugins/SpinePlugin/Intermediate/Build/Android/UE4/Inc/SpinePlugin/SpinePlugin.generated.cpp:function USpineSkeletonDataAsset::USpineSkeletonDataAsset(FVTableHelper&): error: undefined 
reference to 'vtable for USpineSkeletonDataAsset'
LogPlayLevel: UnrealBuildTool: C:/NVPACK/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
LogPlayLevel: UnrealBuildTool: C:/Unreal/spine-ue4/Plugins/SpinePlugin/Binaries/Android/UE4-SpinePlugin-armv7-es2.a(SpinePlugin.generated.cpp-armv7-es2.o):C:/Unreal/spine-ue4/Plugins/SpinePlugin/Intermediate/Build/Android/UE4/Inc/SpinePlugin/SpinePlugin.generated.cpp:function USpineAtlasAsset::USpineAtlasAsset(FObjectInitializer const&): error: undefined ref
erence to 'vtable for USpineAtlasAsset'
LogPlayLevel: UnrealBuildTool: C:/NVPACK/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
LogPlayLevel: UnrealBuildTool: C:/Unreal/spine-ue4/Plugins/SpinePlugin/Binaries/Android/UE4-SpinePlugin-armv7-es2.a(SpinePlugin.generated.cpp-armv7-es2.o):C:/Unreal/spine-ue4/Plugins/SpinePlugin/Intermediate/Build/Android/UE4/Inc/SpinePlugin/SpinePlugin.generated.cpp:function USpineSkeletonDataAsset::USpineSkeletonDataAsset(FObjectInitializer const&): error:
 undefined reference to 'vtable for USpineSkeletonDataAsset'
LogPlayLevel: UnrealBuildTool: C:/NVPACK/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: the vtable symbol may be undefined because the class is missing its key function (see go/missingkeymethod)
LogPlayLevel: UnrealBuildTool: clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
LogPlayLevel: UnrealBuildTool: ERROR: UBT ERROR: Failed to produce item: C:\Unreal\spine-ue4\Binaries\Android\SpineUE4-armv7-es2.so
LogPlayLevel: UnrealBuildTool: Total build time: 24,44 seconds (Local executor: 0,00 seconds)
LogPlayLevel: CommandUtils.Run: Run: Took 24,9894293s to run UnrealBuildTool.exe, ExitCode=5
LogPlayLevel: Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.15\Engine\Binaries\DotNET\UnrealBuildTool.exe SpineUE4 Android Development -Project=C:\Unreal\spine-ue4\SpineUE4.uproject  C:\Unreal\spine-ue4\SpineUE4.uproject  -remotein
i="C:\Unreal\spine-ue4" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2017.05.22-18.52.32.txt'
LogPlayLevel:    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
LogPlayLevel:    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback)
LogPlayLevel:    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars)
LogPlayLevel:    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTargetToManifest)
LogPlayLevel:    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask)
LogPlayLevel:    at BuildCookRun.DoBuildCookRun(ProjectParams Params)
LogPlayLevel:    at BuildCookRun.ExecuteBuild()
LogPlayLevel:    at AutomationTool.BuildCommand.Execute()
LogPlayLevel:    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands)
LogPlayLevel:    at AutomationTool.Automation.Process(String[] Arguments)
LogPlayLevel:    at AutomationTool.Program.MainProc(Object Param)
LogPlayLevel:    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param)
LogPlayLevel:    at AutomationTool.Program.Main()
LogPlayLevel: Program.Main: AutomationTool exiting with ExitCode=5 (5)
LogPlayLevel: Completed Launch On Stage: Build Task, Time: 27.263444
LogPlayLevel: BUILD FAILED
PackagingResults:Error: Error Launch failed! Unknown Error
```

**Comment by badlogic** [comment]
Which version of the Spine UE4 plugin do you use (Master or 3.6-beta branch)? Which UE4 version do you use (4.15.2 or earlier)? Can you try a full clean of the Android build, and rebuild?

**Comment by GerodruS** [comment]
Spine UE4 plugin version is from Master branch. UE4 version is 4.15.2. I've tried check and uncheck ProjectSettings -> Packaging -> Project -> Full Rebuild flag. Is there another way to full rebuild?

**Comment by badlogic** [comment]
That should do the trick. Could you gice the 3.6-beta branch a try? I see
if I can reproduce the issue locally.

**Comment by GerodruS** [comment]
Sorry for the delayed response.
I've tried 3.6-beta branch and it's working.
Thank you for advice.

**Comment by badlogic** [comment]
Great! Thanks for trying.
